# SPDX-FileCopyrightText: Copyright 2025 Todd Schulman
#
# SPDX-License-Identifier: Apache-2.0 OR BSD-2-Clause OR GPL-3.0-or-later

---
name: Build Universal Binary

on:
  release:
    types: [published]

permissions: {}

jobs:
  build:
    if: github.repository == 'toobuntu/powerstatus'
    runs-on: macos-latest
    permissions:
      # for: actions/checkout
      # contents: read # included in contents: write
      # for: actions/attest-build-provenance
      id-token: write
      # contents: read # included in contents: write
      attestations: write
      # for: gh release upload
      contents: write

    steps:
      - name: Checkout code
        # contents: read
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Swift
        uses: swift-actions/setup-swift@d4537ff835c9778c934e48f78639e270edd5839e # v2.2.0

      - name: Build arm64 architecture
        run: |
          mkdir -p ./build
          xcrun swiftc -Osize -target arm64-apple-macos13 -o ./build/powerstatus_arm64 ./src/powerstatus.swift

      - name: Build x86_64 architecture
        run: |
          xcrun swiftc -Osize -target x86_64-apple-macos13 -o ./build/powerstatus_x86_64 ./src/powerstatus.swift

      - name: Create universal binary with lipo
        run: |
          mkdir -p ./bin
          xcrun lipo -create -output ./bin/powerstatus ./build/powerstatus_x86_64 ./build/powerstatus_arm64

      - name: Check binary
        run: |
          file ./bin/powerstatus
          xcrun lipo -archs ./bin/powerstatus

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: "./bin/powerstatus"

      - name: Upload binary as release artifact
        run: |
          gh release \
            upload ${{github.event.release.tag_name}} "./bin/powerstatus" \
            --repo ${{ github.repository }}
        env:
          # NOTE: Use github.token instead of secrets.GITHUB_TOKEN
          # ref https://github.com/cli/cli/issues/6534
          # The issue mentions that secrets.GITHUB_TOKEN is "only available in workflows and not composite actions". But github.token works in all parts of GitHub Actions, including composite actions.
          # Composite actions (in .github/actions) are like functions for workflows (in .github/workflows).
          # ref https://github.com/cli/cli/blob/722fc6734210517706d9844eec3bd66016dfee80/pkg/cmd/root/help.go#L202-L209 # retrieved 21 Jan 2025
          GH_TOKEN: ${{ github.token }}
